// <auto-generated />
using System;
using MKW.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MKW.Data.Context.Migrations
{
    [DbContext(typeof(MKWContext))]
    [Migration("20230503214045_changeImageURLToAllowNulls")]
    partial class changeImageURLToAllowNulls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<int>("PlatformCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("PlatformCategoryId");

                    b.ToTable("TB_MKW_CONTENT", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.ContentGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("CONTENT_ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("GENRE_ID");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("GenreId");

                    b.ToTable("TB_MKW_CONTENT_GENRE", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.ToTable("TB_MKW_GENRE", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.ToTable("TB_MKW_PLATFORM", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.PlatformCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasColumnName("PLATFORM_ID");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("TB_MKW_PLATFORM_CATEGORY", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.IdentityAggregate.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.PremiumAggregate.PremiumPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<bool>("AutoRenewal")
                        .HasColumnType("bit")
                        .HasColumnName("AUTORENEWAL");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("END_DATE");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PERSON_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("START_DATE");

                    b.Property<int>("TierPlanId")
                        .HasColumnType("int")
                        .HasColumnName("TIER_PLAN_ID");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TierPlanId");

                    b.ToTable("TB_PRM_PREMIUM_PERSON", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.PremiumAggregate.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit")
                        .HasColumnName("IS_PREMIUM");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.ToTable("TB_PRM_TIER", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.PremiumAggregate.TierPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("PRICE");

                    b.Property<int>("TierId")
                        .HasColumnType("int")
                        .HasColumnName("TIER_ID");

                    b.Property<int>("TimespanId")
                        .HasColumnType("int")
                        .HasColumnName("TIMESPAN_ID");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("TierId");

                    b.HasIndex("TimespanId");

                    b.ToTable("TB_PRM_TIER_PLAN", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.PremiumAggregate.Timespan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("Days")
                        .HasColumnType("int")
                        .HasColumnName("DAYS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.ToTable("TB_PRM_TIMESPAN", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("PRICE");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.ToTable("TB_RVW_AWARD", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.AwardPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<int>("AwardId")
                        .HasColumnType("int")
                        .HasColumnName("AWARD_ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PERSON_ID");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("REVIEW_ID");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ReviewId");

                    b.ToTable("TB_RVW_AWARD_PERSON", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int?>("ParentComentId")
                        .HasColumnType("int")
                        .HasColumnName("PARENT_COMMENT_ID");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PERSON_ID");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("POST_ID");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ParentComentId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ReviewId");

                    b.ToTable("TB_RVW_COMMENT", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.CommentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<int>("CommentId")
                        .HasColumnType("int")
                        .HasColumnName("COMMENT_ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TEXT");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("TB_RVW_COMMENT_DETAILS", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("CONTENT_ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PERSON_ID");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("PersonId");

                    b.ToTable("TB_RVW_REVIEW", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.ReviewDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("POST_ID");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("TB_RVW_REVIEW_DETAILS", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.AgeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("FinalAge")
                        .HasColumnType("int")
                        .HasColumnName("FINAL_AGE");

                    b.Property<int>("InitialAge")
                        .HasColumnType("int")
                        .HasColumnName("INITIAL_AGE");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.ToTable("TB_USR_AGE_RANGE", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PERSON_ID");

                    b.Property<int>("StarCoins")
                        .HasColumnType("int")
                        .HasColumnName("STAR_COINS");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("TB_USR_BALANCE", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool>("IsBinary")
                        .HasColumnType("bit")
                        .HasColumnName("IS_BINARY");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.ToTable("TB_USR_GENDER", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("BIRTHDATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("GENDER_ID");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMAGE_URL");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("UserId");

                    b.ToTable("TB_USR_PERSON", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.PersonChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<int>("AgeRangeId")
                        .HasColumnType("int")
                        .HasColumnName("AGE_RANGE_ID");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("GENDER_ID");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PERSON_ID");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("AgeRangeId");

                    b.HasIndex("GenderId");

                    b.HasIndex("PersonId");

                    b.ToTable("TB_USR_PERSON_CHILD", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("AlterDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ALTER_DATE");

                    b.Property<int>("BalanceId")
                        .HasColumnType("int")
                        .HasColumnName("BALANCE_ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("int")
                        .HasColumnName("CURRENT_BALANCE");

                    b.Property<int>("NewBalance")
                        .HasColumnType("int")
                        .HasColumnName("NEW_BALANCE");

                    b.Property<bool>("Operation")
                        .HasColumnType("bit")
                        .HasColumnName("OPERATION");

                    b.Property<Guid?>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.HasIndex("BalanceId");

                    b.ToTable("TB_USR_TRANSACTION", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.Content", b =>
                {
                    b.HasOne("MKW.Domain.Entities.ContentAggregate.PlatformCategory", "PlatformCategory")
                        .WithMany("Contents")
                        .HasForeignKey("PlatformCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlatformCategory");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.ContentGenre", b =>
                {
                    b.HasOne("MKW.Domain.Entities.ContentAggregate.Content", "Content")
                        .WithMany("ContentGenre")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.ContentAggregate.Genre", "Genre")
                        .WithMany("ContentGenre")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.PlatformCategory", b =>
                {
                    b.HasOne("MKW.Domain.Entities.ContentAggregate.Platform", "Platform")
                        .WithMany("PlatformCategories")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("MKW.Domain.Entities.PremiumAggregate.PremiumPerson", b =>
                {
                    b.HasOne("MKW.Domain.Entities.UserAggregate.Person", "Person")
                        .WithMany("PremiumPerson")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.PremiumAggregate.TierPlan", "TierPlan")
                        .WithMany("PremiumPerson")
                        .HasForeignKey("TierPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("TierPlan");
                });

            modelBuilder.Entity("MKW.Domain.Entities.PremiumAggregate.TierPlan", b =>
                {
                    b.HasOne("MKW.Domain.Entities.PremiumAggregate.Tier", "Tier")
                        .WithMany("TierPlans")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.PremiumAggregate.Timespan", "Timespan")
                        .WithMany("TierPlans")
                        .HasForeignKey("TimespanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");

                    b.Navigation("Timespan");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.AwardPerson", b =>
                {
                    b.HasOne("MKW.Domain.Entities.ReviewAggregate.Award", "Award")
                        .WithMany("AwardPerson")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.UserAggregate.Person", "Person")
                        .WithMany("AwardsGiven")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.ReviewAggregate.Review", "Review")
                        .WithMany("Awards")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Person");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.Comment", b =>
                {
                    b.HasOne("MKW.Domain.Entities.ReviewAggregate.Comment", "ParentComment")
                        .WithMany("Answers")
                        .HasForeignKey("ParentComentId");

                    b.HasOne("MKW.Domain.Entities.UserAggregate.Person", "Person")
                        .WithMany("Comments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.ReviewAggregate.Review", "Review")
                        .WithMany("Comments")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Person");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.CommentDetails", b =>
                {
                    b.HasOne("MKW.Domain.Entities.ReviewAggregate.Comment", "Comment")
                        .WithMany("CommentDetails")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.Review", b =>
                {
                    b.HasOne("MKW.Domain.Entities.ContentAggregate.Content", "Content")
                        .WithMany("Reviews")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.UserAggregate.Person", "Person")
                        .WithMany("Reviews")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.ReviewDetails", b =>
                {
                    b.HasOne("MKW.Domain.Entities.ReviewAggregate.Review", "Review")
                        .WithMany("ReviewDetails")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.Balance", b =>
                {
                    b.HasOne("MKW.Domain.Entities.UserAggregate.Person", "Person")
                        .WithOne("Balance")
                        .HasForeignKey("MKW.Domain.Entities.UserAggregate.Balance", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.Person", b =>
                {
                    b.HasOne("MKW.Domain.Entities.UserAggregate.Gender", "Gender")
                        .WithMany("People")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.IdentityAggregate.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.PersonChild", b =>
                {
                    b.HasOne("MKW.Domain.Entities.UserAggregate.AgeRange", "AgeRange")
                        .WithMany("Children")
                        .HasForeignKey("AgeRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.UserAggregate.Gender", "Gender")
                        .WithMany("Children")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.UserAggregate.Person", "Person")
                        .WithMany("Children")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AgeRange");

                    b.Navigation("Gender");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.Transaction", b =>
                {
                    b.HasOne("MKW.Domain.Entities.UserAggregate.Balance", "Balance")
                        .WithMany("Transactions")
                        .HasForeignKey("BalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balance");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MKW.Domain.Entities.IdentityAggregate.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MKW.Domain.Entities.IdentityAggregate.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MKW.Domain.Entities.IdentityAggregate.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MKW.Domain.Entities.IdentityAggregate.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.Content", b =>
                {
                    b.Navigation("ContentGenre");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.Genre", b =>
                {
                    b.Navigation("ContentGenre");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.Platform", b =>
                {
                    b.Navigation("PlatformCategories");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ContentAggregate.PlatformCategory", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("MKW.Domain.Entities.PremiumAggregate.Tier", b =>
                {
                    b.Navigation("TierPlans");
                });

            modelBuilder.Entity("MKW.Domain.Entities.PremiumAggregate.TierPlan", b =>
                {
                    b.Navigation("PremiumPerson");
                });

            modelBuilder.Entity("MKW.Domain.Entities.PremiumAggregate.Timespan", b =>
                {
                    b.Navigation("TierPlans");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.Award", b =>
                {
                    b.Navigation("AwardPerson");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.Comment", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("CommentDetails");
                });

            modelBuilder.Entity("MKW.Domain.Entities.ReviewAggregate.Review", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Comments");

                    b.Navigation("ReviewDetails");
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.AgeRange", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.Balance", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.Gender", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("People");
                });

            modelBuilder.Entity("MKW.Domain.Entities.UserAggregate.Person", b =>
                {
                    b.Navigation("AwardsGiven");

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("Children");

                    b.Navigation("Comments");

                    b.Navigation("PremiumPerson");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
